Add Production Build
o2r-project/o2r-UI pull request #200
Opened 2021-01-15 12:16 UTC by Fmazin

2021-01-15 12:23 UTC, Fmazin commented
As i discussed in #58 the multistage dockerfile for the production build for the ui container seems to work. But when the when the whole docker-compose is started the startpage will throw a bad `502 Bad Gateway`.

2021-01-18 09:36 UTC, nuest requested changes

2021-01-18 09:36 UTC, nuest commented on README.md
> +This project has another docker-compose configuration for the deployment of a production build (file `ui/docker-compose-prod.yml`). This configuration has no `ui` container. Instead the webserver con
The for the multi-stage Docker file seems to be broken. Please also capitalise "Docker" (it's a name).

"Which then hosted through nginx." is not a full sentence.

2021-01-18 09:36 UTC, nuest commented on ui/dev/mime.types
> +    ..........................................
Suggest to remove the placeholder.

Are these _all_ mime types used by the UI, or maybe there is a more extensive list just to be sure?

2021-01-29 13:53 UTC, nuest approved these changes
I could run this locally after forcing a rebuild of the webserver image.

Good work! :100:

2021-01-29 13:54 UTC, merged

2021-01-29 13:55 UTC, nuest commented
@NJaku01 Please try out the new compose configurations - the prerendered UI seems to be noticeably quicker.

Note that you have to use a different `docker-compose` command now to run the development version of the UI - see `README.md` !